version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  ApplicationStop:
    - location: deploy/scripts/stop.sh
  BeforeInstall:
    - location: deploy/scripts/install.sh
  AfterInstall:
    - location: deploy/scripts/start.sh